"""
§7.2.3 — a simple dashboard view of a published OPL (One-Page Learning). The durable artifact is
the markdown file itself (data/opl/{project_id}.md, §7.2.3) and the kb_documents row Agent 2/5 read
back (§7.2.4); this is just a readable wrapper so a PMO can see it inline in the composer's middle
panel, same as any other dashboard page.
"""
import sys, os, html as html_lib
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

CSS = """
body{font-family:-apple-system,Helvetica,Arial,sans-serif;max-width:720px;margin:2rem auto;padding:0 1rem;color:#1a1a1a}
.nav{font-size:12px;margin-bottom:16px}
.nav a{color:#378ADD;text-decoration:none;margin-right:14px}
.banner{background:#eaf3de;border:1px solid #a8d18d;border-radius:8px;padding:12px 16px;margin-bottom:20px;font-size:13px}
.banner b{color:#3b6d11}
.grounding{font-size:11px;color:#888;margin-bottom:16px}
.opl-body{background:#fff;border:1px solid #e5e3dc;border-radius:8px;padding:20px 24px;white-space:pre-wrap;line-height:1.7;font-size:14px}
.opl-body h1,.opl-body h2{font-family:inherit}
"""

def render(project_id, project, composed):
    dropped = composed.get("dropped_ungrounded", 0)
    grounding_note = (
        f"{len(composed.get('citations', []))} grounded citation(s) kept"
        + (f", {dropped} ungrounded claim(s) dropped" if dropped else "")
    )
    opl_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "data", "opl", f"{project_id}.md"))
    body_text = ""
    if os.path.isfile(opl_path):
        with open(opl_path, "r") as f:
            body_text = f.read()

    html = f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>OPL — {html_lib.escape(project_id)}</title>
<style>{CSS}</style></head><body>
<div class="nav"><a href="/dashboard/topline.html" target="_top">← Dashboard</a></div>
<div class="banner"><b>One-Page Learning published.</b> Generated by Agent 13 (§7.2.3) on project
completion — auto-published, not gated (PMO can edit the underlying file any time). Now part of the
corpus Agent 2 (§7.2.4) checks new submissions against, and Agent 5 can surface as a "similar past
project" note for future proposals.</div>
<div class="grounding">{grounding_note}</div>
<div class="opl-body">{html_lib.escape(body_text)}</div>
</body></html>"""
    out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), f"opl_{project_id}.html"))
    with open(out_path, "w") as f:
        f.write(html)
    return out_path

if __name__ == "__main__":
    print("This page is meant to be generated mid-flow by scripts/demo_server.py, not run standalone.")
